import type { NextPage, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import Navbar from '../components/common/Navbar'
import Home from '../components/Home'
import { offset, limit } from '../src/api/api'
import { IPost } from '../src/types/post'
import { CountTag } from '../src/types/tag'

const index: NextPage<Props> = ({ posts, postCount, tags }) => {
  return (
    <div>
      <Head>
        <title>{process.env.NEXT_PUBLIC_APP_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Home posts={posts} postCount={postCount} tags={tags} />
      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps = async () => {
  const postUrl = `${process.env.API_URL}/posts/${process.env.AUTHOR_ID}?offset=${offset}&limit=${limit}`

  const tagUrl = `${process.env.API_URL}/tags/count/${process.env.AUTHOR_ID}?limit=${limit}`

  const postRes = await axios.get<[IPost[], number]>(postUrl)
  const tagRes = await axios.get<CountTag[]>(tagUrl)

  return {
    props: {
      posts: postRes.data[0],
      postCount: postRes.data[1],
      tags: tagRes.data,
    },
  }
}

type Props = InferGetStaticPropsType<typeof getStaticProps>

export default index
