import { NextPage, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import styles from '../styles/Home.module.css'
import Home from '../components/Home'
import { IPost } from '../src/types/post'
import { offset, limit, authorId } from '../src/utils/api/api'
import Posts from '../components/posts/Posts'

const index: NextPage<Props> = ({ posts }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Havasu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home />
      <Posts posts={posts} />

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps = async () => {
  const url = `${process.env.API_URL}/posts/${authorId}?offset=${offset}&limit=${limit}`

  const res = await axios.get<IPost[]>(url)
  return {
    props: { posts: res.data },
  }
}

type Props = InferGetStaticPropsType<typeof getStaticProps>

export default index
