import type { NextPage, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import Navbar from '../components/common/Navbar'
import Home from '../components/Home'
import { offset, limit } from '../src/api/api'
import { IPost } from '../src/types/post'

const index: NextPage<Props> = ({ posts }) => {
  return (
    <div>
      <Head>
        <title>{process.env.NEXT_PUBLIC_APP_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Home posts={posts} />
      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps = async () => {
  const url = `${process.env.API_URL}/posts/${process.env.AUTHOR_ID}?offset=${offset}&limit=${limit}`
  const res = await axios.get<IPost[]>(url)

  return {
    props: { posts: res.data },
  }
}

type Props = InferGetStaticPropsType<typeof getStaticProps>

export default index
